[package]
name = "rusty-finance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#clap = "4.3.0"
clap = { version = "4.3.0", features = ["derive"] }
prettytable-rs = "0.10.0"
